// PM2 Ecosystem File for server-nest
// 使用方式: pm2 start ecosystem.config.js --env dev|staging|prod

module.exports = {
  apps: [
    {
      name: 'server-nest-dev',
      script: 'dist/main.js',
      cwd: '/var/jenkins_home/workspace/server-nest',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'dev',
        PORT: 8118,
        DB_HOST: 'host.docker.internal',
        DB_PORT: 3307,
        DB_USERNAME: 'root',
        DB_PASSWORD: 'root123',
        DB_DATABASE: 'together_dev',
        REDIS_HOST: 'host.docker.internal',
        REDIS_PORT: 6383,
        RUSTFS_URL: 'http://host.docker.internal:8121',
      },
      error_file: '/var/log/pm2/server-nest-dev-error.log',
      out_file: '/var/log/pm2/server-nest-dev-out.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'server-nest-staging',
      script: 'dist/main.js',
      cwd: '/var/jenkins_home/workspace/server-nest',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 8119,
        DB_HOST: 'host.docker.internal',
        DB_PORT: 3308,
        DB_USERNAME: 'root',
        DB_PASSWORD: 'root123',
        DB_DATABASE: 'together_staging',
        REDIS_HOST: 'host.docker.internal',
        REDIS_PORT: 6384,
        RUSTFS_URL: 'http://host.docker.internal:8122',
      },
      error_file: '/var/log/pm2/server-nest-staging-error.log',
      out_file: '/var/log/pm2/server-nest-staging-out.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'server-nest-prod',
      script: 'dist/main.js',
      cwd: '/var/jenkins_home/workspace/server-nest',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'prod',
        PORT: 8120,
        DB_HOST: 'host.docker.internal',
        DB_PORT: 3309,
        DB_USERNAME: 'root',
        DB_PASSWORD: 'root123',
        DB_DATABASE: 'together_prod',
        REDIS_HOST: 'host.docker.internal',
        REDIS_PORT: 6382,
        RUSTFS_URL: 'http://host.docker.internal:8123',
      },
      error_file: '/var/log/pm2/server-nest-prod-error.log',
      out_file: '/var/log/pm2/server-nest-prod-out.log',
      merge_logs: true,
      time: true,
      kill_timeout: 5000,
      listen_timeout: 10000,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      exp_backoff_restart_delay: 100,
    },
  ],
};
